In [1]:
import numpy as np 

**Three Dimensional Array**

In [2]:
x = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

**3D Array Slicing** 

In [3]:
x[1,1,:]

array([7, 8])

In [4]:
x[:,1,:]

array([[3, 4],
       [7, 8]])

**Modifying 3D Arrays**

In [5]:
x[0,1,:] = [9, 0]

In [6]:
x

array([[[1, 2],
        [9, 0]],

       [[5, 6],
        [7, 8]]])

**Initializing Different Types of Arrays**

In [7]:
# All 0s array
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [8]:
# All ones in the main diagonal
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [9]:
# All 1s matrix
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [10]:
# matrix with specified value
np.full((2,2), (99))

array([[99, 99],
       [99, 99]])

In [11]:
# matrix like another
np.full_like(x, 4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [12]:
# random decimal matrix
np.random.rand(4, 2)

array([[0.54714169, 0.81682907],
       [0.49498264, 0.58484517],
       [0.16912703, 0.6235288 ],
       [0.54278665, 0.65717822]])

In [13]:
# random shape-like matrix in decimals
np.random.random_sample((4,2))

array([[0.96165543, 0.08460416],
       [0.92877058, 0.71542139],
       [0.06699013, 0.94643373],
       [0.16588138, 0.82684088]])

In [14]:
# random integer matrix
np.random.randint((1,9), size= (2, 2))

array([[0, 6],
       [0, 1]])

In [15]:
# repeat matrix
a1 = np.array([[1, 2, 3]])
a2 = np.repeat(a1, 3, axis = 0)
print(a2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


**Example: Build the array below**

<h1>1-D ARRAY</h1>
<img src = array.png height=300px width=300px></img>

In [16]:
output = np.ones((5, 5))
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
sub = np.zeros((3,3))
sub

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
sub[1, 1] = 9
sub

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [19]:
output[1:4, 1:4] = sub

In [20]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

**Arithmetics**

**Linear Algebra**

In [21]:
# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse

In [22]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [23]:
# multiplying matrix
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [24]:
# find determinant of an identity matrix
c = np.identity(2)
np.linalg.det(c)

1.0

In [28]:
# fine the inverse of an identity matrix
np.linalg.inv(c)

array([[1., 0.],
       [0., 1.]])

**Statistics**

In [37]:
# min
arr = np.array([[1, 2], [3, 4]])
arr
print(np.min((arr)))
# max
print(np.max(arr, axis=0))
# sum
print(np.sum(arr))

1
[3 4]
10


In [40]:
# standard deviation
print(np.std(arr))

1.118033988749895


In [44]:
import pandas as pd
df = pd.DataFrame(arr, columns=["No", "ID"])
print(df)
df.describe()

   No  ID
0   1   2
1   3   4


No        ID
count  2.000000  2.000000
mean   2.000000  3.000000
std    1.414214  1.414214
min    1.000000  2.000000
25%    1.500000  2.500000
50%    2.000000  3.000000
75%    2.500000  3.500000
max    3.000000  4.000000

In [47]:
ddf  = df[["No"]]
ddf

No
0   1
1   3

In [48]:
# Turn dataframe into an array 
mkarray = np.array(ddf)
mkarray

array([[1],
       [3]])

**Load Data From File**

In [54]:
filedata = np.genfromtxt("Items.txt", delimiter=",")
filedata = filedata.astype("int32")
filedata

array([[300, 400],
       [100, 290],
       [200, 490],
       [150, 600],
       [135,   5]])

In [60]:
filedata.dtype

dtype('int32')

**Boolean Masking and Advanced Indexing**

In [63]:
np.any(filedata > 50, axis = 1)

array([ True,  True,  True,  True,  True])

In [65]:
filedata[filedata > 50]

array([300, 400, 100, 290, 200, 490, 150, 600, 135])

In [66]:
((filedata > 50) & (filedata < 100))

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

In [68]:
# all values greater than 100 but less than 200
filedata[((filedata > 100) & (filedata < 200))]

array([150, 135])

In [78]:
# not greater than 100 and not less than 200
~(filedata > 100) &  (filedata < 200)

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

In [71]:
filedata

array([[300, 400],
       [100, 290],
       [200, 490],
       [150, 600],
       [135,   5]])

**Example Exercise**

In [88]:
anaray = np.arange(1,31).reshape(6, 5)
anaray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [89]:
anaray[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [95]:
anaray[[0,1,2,3], [1,2,3,4]]

array([ 2,  8, 14, 20])

In [100]:
anaray[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])